wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.10.12
    cli_version: 0.15.9
    framework: huggingface
    huggingface_version: 4.32.0
    is_jupyter_run: true
    is_kaggle_kernel: false
    start_time: 1693485810.604111
    t:
      1:
      - 1
      - 2
      - 3
      - 11
      - 41
      - 49
      - 55
      - 71
      2:
      - 1
      - 2
      - 3
      - 11
      - 41
      - 49
      - 55
      - 71
      3:
      - 23
      4: 3.10.12
      5: 0.15.9
      6: 4.32.0
      8:
      - 1
      - 5
